import { createApp } from 'vue'
import App from './App.vue'
import './registerServiceWorker'
import router from './router'
import store from './store'
import socket from '@/socket/index'
import ElementPlus from 'element-plus'
import 'element-plus/dist/index.css'
// import VueSocketIO from 'vue-socket.io'
createApp(App).use(ElementPlus).use(store).mount('#app')
